name: 🐧 Linux Builds
on:
  push: {}
  pull_request: {}
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of V8 to build'
        # default: 10.3.174.20
        required: false

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-linux
  cancel-in-progress: true

env:
  VERSION: ""

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: 🐧 Linux ${{ matrix.type }} (${{ matrix.target_cpu }})
    strategy:
      fail-fast: false
      matrix:
        target_cpu: [ 'x64' ]
        type: [ 'static', 'dynamic' ]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/v8-version
      with:
        version: ${{ github.inputs.version }}
    - name: Run Build Script
      run: |
        cd ${{ github.workspace }}
        sh ./build.sh linux ${{ matrix.target_cpu }} ${{ matrix.type }} ${{ env.VERSION }}
        # sh ./.github/test/build.sh linux ${{ matrix.target_cpu }} ${{ matrix.type }} ${{ env.VERSION }}
    - uses: actions/upload-artifact@v2
      with:
        name: linux-${{matrix.target_cpu}}
        path: ~/v8/v8/output/**/*
